# Generated by Django 3.2 on 2021-05-01 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing', '0002_auto_20210501_0722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ridedriver',
            old_name='rider',
            new_name='ride',
        ),
    ]
